apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-ui
  template:
    metadata:
      labels:
        app: incident-ui
    spec:
      containers:
        - name: incident-ui
          image: prabhatcr001.azurecr.io/incident-ui:60db9be59e895b5569a736562740ce405a889b5a
          ports:
            - containerPort: 3000