apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-ui
  template:
    metadata:
      labels:
        app: incident-ui
    spec:
      containers:
        - name: incident-ui
          image: prabhatcr001.azurecr.io/incident-ui:1b04791d23544f59d937369e8d7c6af94a6bd8ad
          ports:
            - containerPort: 3000