apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-ui
  template:
    metadata:
      labels:
        app: incident-ui
    spec:
      containers:
        - name: incident-ui
          image: prabhatcr001.azurecr.io/incident-ui:1e099f8dbfb72a1ca465504229f6b72f6fcdb2f5
          ports:
            - containerPort: 3000