name: Frontend CI

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: incident-ui

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login prabhatcr001.azurecr.io \
            -u "${{ secrets.ACR_USERNAME }}" \
            --password-stdin

      - name: Build Docker image
        run: |
          docker build -t prabhatcr001.azurecr.io/$IMAGE_NAME:${{ github.sha }} .
          docker tag prabhatcr001.azurecr.io/$IMAGE_NAME:${{ github.sha }} \
                     prabhatcr001.azurecr.io/$IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          docker push prabhatcr001.azurecr.io/$IMAGE_NAME:${{ github.sha }}
          docker push prabhatcr001.azurecr.io/$IMAGE_NAME:latest